<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-OIGE0TE" failures="1" tests="1" name="Default test(failed)" time="1.93" errors="0" timestamp="2019-11-28T14:02:11 IST">
  <testcase classname="framework.ConfigMethods" name="@AfterMethod writeReport" time="0.026">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at framework.UtilityMethods.capture(UtilityMethods.java:68)
at framework.ConfigMethods.writeReport(ConfigMethods.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod writeReport -->
  <testcase classname="framework.ConfigMethods" name="@AfterTest afterTest" time="0.001">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at framework.ConfigMethods.afterTest(ConfigMethods.java:88)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- @AfterTest afterTest -->
  <testcase classname="tests.createCompanies.CreateNewContactTest" name="enteringPersonalDetails" time="1.712">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at tests.createCompanies.CreateNewContactTest.enteringPersonalDetails(CreateNewContactTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- enteringPersonalDetails -->
  <testcase classname="tests.createCompanies.CreateNewContactTest" name="login" time="0.0">
    <ignored/>
  </testcase> <!-- login -->
  <testcase classname="tests.createCompanies.CreateNewContactTest" name="navigatingToNewcontacts" time="0.0">
    <ignored/>
  </testcase> <!-- navigatingToNewcontacts -->
</testsuite> <!-- Default test(failed) -->
